#
###################################
# Site wide configuration
####################################
#
title: orestkyrylchuk
email: orestkyrylchuk@gmail.com
description: A simple and awesome personal blog powered by jekyll.
url: https://orestkyrylchuk.com # the base hostname & protocol for your site
keywords: ["Java", "Kotlin", "AWS"]

#
###################################
# Jekyll configuration
####################################
#
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

timezone:          America/Vancouver
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /:title
paginate: 5
paginate_path: /articles/page/:num/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Orest Kyrylchuk
  avatar: blog-logo.png
  job: "Software Engineer"
  bio: "<br><b>5+</b> years of experience.
    <br>Originally from Lviv, Ukraine, but currently live in Seattle, WA.
    <br>Blog posts are my own."
  disqus-shortname: orestkyrylchuk
  google:
    analytics: UA-124218867-1
  github: korest #username
  stackoverflow: 2055854/forest
  linkedin: orest-kyrylchuk-3718983b #username
  instagram: orest.kyrylchuk

# Feed configuration
feed:
  path: feed.xml

# SEO configuration
author:
  name: Orest Kyrylchuk
  email: orestkyrylchuk@gmail.com

social:
  name: Orest Kyrylchuk
  links:
    - https://github.com/korest
    - https://linkedin.com/in/orest-kyrylchuk-3718983b
    - https://stackoverflow.com/users/2055854/forest
    - https://instagram.com/orest.kyrylchuk

sass:
  style: compressed

